png(file='Plot3.png')
dataRead<-read.table('household_power_consumption.txt',header=TRUE,na.strings="?",sep=';')
dataRead$Date<-as.Date(dataRead$Date,format="%d/%m/%Y")
data<-subset(dataRead,Date== "2007-02-01" | Date=="2007-02-02" )
data$datime<-strptime(paste(data$Date,data$Time,sep=" "),format="%Y-%m-%d %H:%M:%S")
plot(data$datime,data$Sub_metering_1,type='l',ylab='Energy sub metering',xlab="",col='black')
lines(data$datime,data$Sub_metering_2,col='red')
lines(data$datime,data$Sub_metering_3,col='blue')
legend("topright",col=c('Black','red','blue'),legend=c('Sub_metering_1','Sub_metering_2','Sub_metering_3'),lty=1)
dev.off()